server:
  port: 12346


#########################################################################
# 测试日志都为trace
#
#########################################################################
logging:
  level:
    com.jasmine: debug # 全局配置

