server:
  port: 8080
  servlet:
    session:
      timeout: 30m #30分钟，测试的话时间不能太短，否则不准。m是分钟单位，s是秒的单位，h是小时的单位，不写单位的话默认是毫秒


bjs:
  value:
    name: jasmine


#============== kafka ===================
# 指定kafka 代理地址，可以多个
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092