server:
  port: 12344


spring:
  mvc:
    format:
      # mvc 接收参数时对日期进行格式化
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
  jackson:
    # jackson 对响应回去的日期参数进行格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#  data:
#    #============== ElasticSearch ===================
#    elasticsearch:
#      repositories:
#        enabled: true # 启用 ElasticsearchTemplate
#      cluster-name: docker-cluster    # ES集群名称，在elasticsearch.yml 中配置默 elasticsearch
#      cluster-nodes: bjs-es:9300      # ES集群节点 用逗号分隔 , java连接默9300，http连接默9200
##      properties:
##        path:
##          logs: ./elasticsearch/log   # ES日志存储目录
##          data: ./elasticsearch/data  # ES数据存储目录
#  elasticsearch:
#    rest:
#      uris: bjs-es:9200


#########################################################################
# 测试日志都为trace
#########################################################################
logging:
  level:
    com.jasmine: debug # 全局配置



elasticsearch:
#  discovery-type: single
#  single:
#    node: localhost:9200
  discovery-type: cluster
  cluster:
    nodes: localhost:9200,localhost:9200,localhost:9200


learning:
  description: @description@
  frameworkVersion: @framework.version@