server:
  port: 12345

spring:
  mvc:
    format:
      # mvc 接收参数时对日期进行格式化
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
  jackson:
    # jackson 对响应回去的日期参数进行格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#########################################################################
# 测试日志都为trace
#########################################################################
logging:
  level:
    com.jasmine: DEBUG # 全局配置
    com.jasmine.feign: DEBUG

learning:
  description: @description@
  frameworkVersion: @framework.version@