server:
  port: 8080


spring:
  data:
    #============== ElasticSearch ===================
    elasticsearch:
      repositories:
        enabled: true # 启用 ElasticsearchTemplate
      cluster-name: docker-cluster    # ES集群名称，在elasticsearch.yml 中配置默 elasticsearch
      cluster-nodes: bjs-es:9300      # ES集群节点 用逗号分隔 , java连接默9300，http连接默9200
#      properties:
#        path:
#          logs: ./elasticsearch/log   # ES日志存储目录
#          data: ./elasticsearch/data  # ES数据存储目录
  elasticsearch:
    rest:
      uris: bjs-es:9200
  #============== kafka ===================
  # 指定kafka 代理地址，可以多个
  kafka:
    bootstrap-servers: bjs-kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: learning-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    com.jasmine.learingsb: trace


bjs:
  value:
    name: jasmine
